before_install:
  - sudo apt-get update
  - sudo apt-get install hunspell
  - sudo apt-get install myspell-en-us
  - sudo apt-get install myspell-it
  - sudo apt-get install python2.7
jobs:
  include:
    - stage: test
      name: "orthography"
      script: bash scripts/grammar.sh
notifications:
  slack: zerosevengroup:awH2p9uSzEPY9plMSyKBtAHF
