dist: trusty
stages:
  - "grammar"
  - "gulpease"
jobs:
  include:
    - stage: "grammar"
      script:
       - sudo apt-get update
       - sudo apt-get install hunspell
       - sudo apt-get install myspell-en-us
       - sudo apt-get install myspell-it
       - bash scripts/grammar.sh
    - stage: "gulpease"
      script:
        - sudo apt-get install python-dev libxml2-dev libxslt1-dev antiword unrtf poppler-utils pstotext tesseract-ocr flac lame libmad0 libsox-fmt-mp3 sox libjpeg-dev swig libpulse-dev
        - pip install --user textract 
        - cd scripts
        - python gulpease.py
notifications:
  slack: zerosevengroup:awH2p9uSzEPY9plMSyKBtAHF
