before_install:
  - sudo apt-get update
  - sudo apt-get install hunspell
  - sudo apt-get install myspell-en-us
  - sudo apt-get install myspell-it
  - sudo apt-get install python-dev libxml2-dev libxslt1-dev antiword unrtf poppler-utils pstotext tesseract-ocr flac lame libmad0 libsox-fmt-mp3 sox libjpeg-dev swig libpulse-dev
  - pip install --user textract 
  - sudo apt-get install texlive-latex-base
jobs:
  include:
    - stage: test
      name: "orthography"
      script: 
       - bash scripts/grammar.sh
      after_success:
       - pdflatex -halt-on-error Esterni/PianoDiProgetto/PianoDiProgetto.tex 
       - python scripts/gulpease.py 

notifications:
  slack: zerosevengroup:awH2p9uSzEPY9plMSyKBtAHF
