before_install:
  - sudo apt-get update
  - sudo apt-get install hunspell
  - sudo apt-get install myspell-en-us
  - sudo apt-get install myspell-it
jobs:
  include:
    - stage: test
      name: "orthography"
      script: bash scripts/grammar.sh
notifications:
  slack: zerosevengroup:awH2p9uSzEPY9plMSyKBtAHF
    on_success: always
    on_failure: always 
