before_install:
  - sudo apt-get update
  - sudo apt-get install hunspell
  - sudo apt-get install myspell-en-us
  - sudo apt-get install myspell-it
jobs:
  include:
    - stage: test
      name: "orthography"
      script: bash grammar.sh
