stages:
  - "grammar"
  - "compile"
    if: (branch = develop) OR (branch = master)
before_install:
  - sudo apt-get update
  - sudo apt-get install hunspell
  - sudo apt-get install myspell-en-us
  - sudo apt-get install myspell-it
  - sudo apt-get install python-dev libxml2-dev libxslt1-dev antiword unrtf poppler-utils pstotext tesseract-ocr flac lame libmad0 libsox-fmt-mp3 sox libjpeg-dev swig libpulse-dev
  - pip install --user textract 
  - sudo apt-get install -y --no-install-recommends texlive-full
jobs:
  include:
    - stage: "grammar"
      script:
       - bash scripts/grammar.sh
    - stage: "compile"
      script:
        - cd Esterni
notifications:
  slack: zerosevengroup:awH2p9uSzEPY9plMSyKBtAHF
